package client.model;

public enum AbilityName {
    SENTRY_ATTACK, SENTRY_DODGE, SENTRY_RAY,
    BLASTER_ATTACK, BLASTER_DODGE, BLASTER_BOMB,
    HEALER_ATTACK, HEALER_DODGE, HEALER_HEAL,
    GUARDIAN_ATTACK, GUARDIAN_DODGE, GUARDIAN_FORTIFY,
    SHADOW_ATTACK, SHADOW_DODGE, SHADOW_SLASH
}
